import type { Vault } from './types'

export const MOCK_VAULTS: Vault[] = [
  {
    id: 'alpine-alpha',
    address: '0xA11a000000000000000000000000000000000001',
    name: 'Alpine Alpha',
    symbol: 'ALPA',
    description:
      'A concentrated portfolio built around durable AI infrastructure, selective mobility and cash-generative platforms. Every position must have a clear catalyst and a defined invalidation point.',
    manager: {
      name: 'Sofia Lindqvist',
      handle: '@sofia.eth',
      avatar: '/twitter1.jpg',
      bio: 'Former public-markets analyst. Long-duration ideas, short feedback loops.',
      socials: { x: '#', telegram: '#', website: '#' },
    },
    perfTotal: '+87%',
    perf7d: '+3.1%',
    nav: '$1.248',
    sharePriceUsd: 1.248,
    members: 248,
    coverK: 8,
    access: {
      hasAccess: true,
      status: 'open',
      minDeposit: 250,
      maxDeposit: 15_000,
      availableCapacity: 38_420,
      entryFeeBps: 75,
      entryFeeMode: 'fixed',
      depositWindow: 'Open · daily batches',
      nextBatch: 'Today · 18:00 UTC',
      withdrawalCooldown: '24 hours',
      accessPolicy: 'Open to any wallet · no KYC',
    },
    mandate: 'High-conviction US equities · 5–12 positions',
    nextSettlement: '11d 08h',
    trades: [
      { side: 'B', ticker: 'NVDA', size: '$12.4k', ago: '2h', note: 'Added on datacenter guidance' },
      { side: 'S', ticker: 'TSLA', size: '$8.2k', ago: '6h', note: 'Trimmed into strength' },
      { side: 'B', ticker: 'AAPL', size: '$5.0k', ago: '1d', note: 'Started services thesis' },
    ],
    theses: [
      {
        id: 'alpine-thesis-1',
        title: 'Compute remains the bottleneck',
        body: 'Demand is broadening beyond model training. We are watching inference economics, networking constraints and the rate at which hyperscalers convert backlog into deployed capacity.',
        tags: ['AI infrastructure', 'NVDA'],
        updatedAt: 'Updated 2h ago',
        pinned: true,
      },
      {
        id: 'alpine-thesis-2',
        title: 'Mobility: protect the downside',
        body: 'We reduced exposure after the latest run. Re-entry requires improving automotive margins or a clearer software revenue inflection.',
        tags: ['Mobility', 'Risk'],
        updatedAt: 'Updated yesterday',
      },
    ],
    chat: [
      {
        id: 'alpine-chat-1',
        user: '@sofia.eth',
        avatar: '/twitter1.jpg',
        time: '10:42',
        body: 'I posted the updated compute thesis above. The key change is our sizing rule, not the long-term view.',
        role: 'manager',
      },
      {
        id: 'alpine-chat-2',
        user: '@lucas',
        avatar: '/twitter4.jpg',
        time: '10:47',
        body: 'Does the NVDA add use all the cash buffer or are we keeping room for the next print?',
        role: 'member',
      },
      {
        id: 'alpine-chat-3',
        user: '@sofia.eth',
        avatar: '/twitter1.jpg',
        time: '10:51',
        body: 'Keeping 9% in USDG. I want optionality around earnings.',
        role: 'manager',
      },
    ],
    activity: [
      { id: 'aa-1', type: 'trade', title: 'Bought NVDA', detail: '$12.4k · 9.8% of NAV', time: '2h', tone: 'green' },
      { id: 'aa-2', type: 'thesis', title: 'Thesis revised', detail: 'Compute remains the bottleneck', time: '2h', tone: 'blue' },
      { id: 'aa-3', type: 'trade', title: 'Sold TSLA', detail: '$8.2k · reduced to 6.1%', time: '6h', tone: 'red' },
      { id: 'aa-4', type: 'member', title: '3 new members', detail: '$4.1k queued for next batch', time: '8h', tone: 'neutral' },
    ],
    position: {
      value: 14_180,
      netInvested: 12_000,
      pnl: 2_180,
      pnlPercent: 18.2,
      shares: 11_362.18,
      allocationPercent: 28.4,
      history: [
        { label: 'May 1', value: 12_000 },
        { label: 'May 6', value: 12_280 },
        { label: 'May 11', value: 12_120 },
        { label: 'May 16', value: 12_760 },
        { label: 'May 21', value: 13_050 },
        { label: 'May 26', value: 12_890 },
        { label: 'Jun 1', value: 13_620 },
        { label: 'Today', value: 14_180 },
      ],
      events: [
        { pointIndex: 2, ticker: 'TSLA', side: 'S', label: 'Trimmed TSLA' },
        { pointIndex: 4, ticker: 'AAPL', side: 'B', label: 'Opened AAPL' },
        { pointIndex: 6, ticker: 'NVDA', side: 'B', label: 'Added NVDA' },
      ],
    },
  },
  {
    id: 'blue-chip-basket',
    address: '0xB1ue000000000000000000000000000000000002',
    name: 'Blue Chip Basket',
    symbol: 'BLUE',
    description:
      'A low-turnover basket of category leaders designed to compound through full market cycles, with disciplined rebalancing around valuation and concentration.',
    manager: {
      name: 'Luca Marchetti',
      handle: '@marchetti',
      avatar: '/twitter2.jpg',
      bio: 'Quality-first investor focused on durable free cash flow.',
      socials: { x: '#', telegram: '#', website: '#' },
    },
    perfTotal: '+34%',
    perf7d: '+1.8%',
    nav: '$1.091',
    sharePriceUsd: 1.091,
    members: 512,
    coverK: 40,
    access: {
      hasAccess: false,
      status: 'open',
      minDeposit: 500,
      maxDeposit: 25_000,
      availableCapacity: 92_600,
      entryFeeBps: 120,
      entryFeeMode: 'dynamic',
      depositWindow: 'Open · weekdays',
      nextBatch: 'Tomorrow · 15:30 UTC',
      withdrawalCooldown: '24 hours',
      accessPolicy: 'Open to any wallet · no KYC',
    },
    mandate: 'Large-cap compounders · quarterly rebalance',
    nextSettlement: '18d 08h',
    trades: [
      { side: 'B', ticker: 'MSFT', size: '$22.0k', ago: '4h', note: 'Rebalanced cloud exposure' },
      { side: 'B', ticker: 'SPY', size: '$15.5k', ago: '9h', note: 'Deployed monthly inflows' },
      { side: 'S', ticker: 'NVDA', size: '$6.3k', ago: '2d', note: 'Capped concentration' },
    ],
    theses: [
      {
        id: 'blue-thesis-1',
        title: 'Compounding over prediction',
        body: 'We prefer businesses that can reinvest at high incremental returns. Price matters, but durability determines the holding period.',
        tags: ['Quality', 'Long term'],
        updatedAt: 'Updated 4h ago',
        pinned: true,
      },
    ],
    chat: [
      { id: 'blue-chat-1', user: '@marchetti', avatar: '/twitter2.jpg', time: '09:12', body: 'Monthly rebalance is complete. No change to the core thesis.', role: 'manager' },
      { id: 'blue-chat-2', user: '@maya', avatar: '/twitter5.jpg', time: '09:20', body: 'The lower turnover is exactly why I joined this one.', role: 'member' },
    ],
    activity: [
      { id: 'blue-1', type: 'trade', title: 'Bought MSFT', detail: '$22.0k · rebalance', time: '4h', tone: 'green' },
      { id: 'blue-2', type: 'member', title: '8 deposits queued', detail: '$18.6k for next batch', time: '7h', tone: 'neutral' },
      { id: 'blue-3', type: 'trade', title: 'Bought SPY', detail: '$15.5k · core allocation', time: '9h', tone: 'green' },
    ],
    position: {
      value: 0,
      netInvested: 0,
      pnl: 0,
      pnlPercent: 0,
      shares: 0,
      allocationPercent: 0,
      history: [
        { label: 'May 1', value: 10_000 }, { label: 'May 6', value: 10_060 }, { label: 'May 11', value: 10_180 },
        { label: 'May 16', value: 10_120 }, { label: 'May 21', value: 10_310 }, { label: 'May 26', value: 10_420 },
        { label: 'Jun 1', value: 10_690 }, { label: 'Today', value: 10_910 },
      ],
      events: [
        { pointIndex: 3, ticker: 'SPY', side: 'B', label: 'Added SPY' },
        { pointIndex: 6, ticker: 'MSFT', side: 'B', label: 'Rebalanced MSFT' },
      ],
    },
  },
  {
    id: 'momentum-seven',
    address: '0x7000000000000000000000000000000000000007',
    name: 'Momentum Seven',
    symbol: 'M7',
    description:
      'A tactical seven-name portfolio following earnings revisions, relative strength and liquidity. Positions are actively resized as evidence changes.',
    manager: {
      name: 'Kenji Tanaka',
      handle: '@kenji_t',
      avatar: '/twitter3.jpg',
      bio: 'Systematic momentum with discretionary risk controls.',
      socials: { x: '#', telegram: '#', website: '#' },
    },
    perfTotal: '+129%',
    perf7d: '+5.6%',
    nav: '$1.412',
    sharePriceUsd: 1.412,
    members: 97,
    coverK: 12,
    access: {
      hasAccess: false,
      status: 'paused',
      minDeposit: 1_000,
      maxDeposit: 10_000,
      availableCapacity: 7_350,
      entryFeeBps: 180,
      entryFeeMode: 'dynamic',
      depositWindow: 'Paused · capacity review',
      nextBatch: 'Reopens in ~3 days',
      withdrawalCooldown: '24 hours',
      accessPolicy: 'Open to any wallet · no KYC',
    },
    mandate: 'Seven liquid leaders · active risk rotation',
    nextSettlement: '04d 18h',
    trades: [
      { side: 'B', ticker: 'TSLA', size: '$9.8k', ago: '1h', note: 'Momentum re-entry' },
      { side: 'B', ticker: 'NVDA', size: '$14.1k', ago: '7h', note: 'Revision breadth improved' },
      { side: 'S', ticker: 'MSFT', size: '$4.4k', ago: '1d', note: 'Relative strength faded' },
    ],
    theses: [
      {
        id: 'm7-thesis-1',
        title: 'Follow revisions, not narratives',
        body: 'The portfolio rotates when earnings expectations and relative strength agree. Conviction never overrides the exit model.',
        tags: ['Momentum', 'Earnings'],
        updatedAt: 'Updated 1h ago',
        pinned: true,
      },
    ],
    chat: [
      { id: 'm7-chat-1', user: '@kenji_t', avatar: '/twitter3.jpg', time: '11:03', body: 'Capacity is paused while we rebalance the smallest sleeve.', role: 'manager' },
      { id: 'm7-chat-2', user: '@ana', avatar: '/twitter4.jpg', time: '11:08', body: 'Will existing queued deposits keep their place?', role: 'member' },
    ],
    activity: [
      { id: 'm7-1', type: 'trade', title: 'Bought TSLA', detail: '$9.8k · momentum entry', time: '1h', tone: 'green' },
      { id: 'm7-2', type: 'settlement', title: 'Deposits paused', detail: 'Capacity review in progress', time: '3h', tone: 'blue' },
      { id: 'm7-3', type: 'trade', title: 'Bought NVDA', detail: '$14.1k · signal confirmed', time: '7h', tone: 'green' },
    ],
    position: {
      value: 0,
      netInvested: 0,
      pnl: 0,
      pnlPercent: 0,
      shares: 0,
      allocationPercent: 0,
      history: [
        { label: 'May 1', value: 10_000 }, { label: 'May 6', value: 10_350 }, { label: 'May 11', value: 10_120 },
        { label: 'May 16', value: 10_880 }, { label: 'May 21', value: 11_060 }, { label: 'May 26', value: 11_940 },
        { label: 'Jun 1', value: 12_410 }, { label: 'Today', value: 14_120 },
      ],
      events: [
        { pointIndex: 2, ticker: 'MSFT', side: 'S', label: 'Exited MSFT' },
        { pointIndex: 5, ticker: 'NVDA', side: 'B', label: 'Added NVDA' },
        { pointIndex: 7, ticker: 'TSLA', side: 'B', label: 'Re-entered TSLA' },
      ],
    },
  },
]

export function getVaultById(id: string) {
  return MOCK_VAULTS.find((vault) => vault.id === id)
}
